name: RedditBrowser
author: Delta2Force
version: 1.7
api-version: 1.13
main: me.delta2force.redditbrowser.RedditBrowserPlugin

commands:
 reddit:
  description: browse reddit in minecraft!
  permission: redditbrowser.browse
 reddit-join:
  description: join a player in an existing lobby.
permissions:
 redditbrowser.browse:
  default: op