name: RedditBrowser
author: u/DeltaTwoForce
version: 1.4
api-version: 1.13
main: me.delta2force.redditbrowser.RedditBrowserPlugin

commands:
 reddit:
  description: browse reddit in minecraft!
  permission: redditbrowser.browse

permissions:
 redditbrowser.browse:
  default: op