name: RedditBrowser
author: Delta2Force
version: 1.6.1
api-version: 1.13
main: me.delta2force.redditbrowser.RedditBrowserPlugin

commands:
 reddit:
  description: browse reddit in minecraft!
  permission: redditbrowser.browse

permissions:
 redditbrowser.browse:
  default: op